% Plot joint values for model and proof model

figure(1);
set(gcf,'color','w');
sgtitle('Evolución de las coord. articulares');
subplot(3,1,1);
plot(out.q.time,out.q.signals.values(:,1));
hold on;
plot(out.q.time,out.q.signals.values(:,2));
hold on;
plot(out.q.time,out.q.signals.values(:,3));
hold on;
plot(out.qp.time,out.qp.signals.values(:,1));
hold on;
plot(out.qp.time,out.qp.signals.values(:,2));
hold on;
plot(out.qp.time,out.qp.signals.values(:,3));
title('q');
legend('q1 modelo','q2 modelo','q3 modelo','q1 proof','q2 proof','q3 proof');
grid;
hold off;
subplot(3,1,2);
plot(out.qd.time,out.qd.signals.values(:,1));
hold on;
plot(out.qd.time,out.qd.signals.values(:,2));
hold on;
plot(out.qd.time,out.qd.signals.values(:,3));
hold on;
plot(out.qdp.time,out.qdp.signals.values(:,1));
hold on;
plot(out.qdp.time,out.qdp.signals.values(:,2));
hold on;
plot(out.qdp.time,out.qdp.signals.values(:,3));
title('qd');
legend('q1d modelo','q2d modelo','q3d modelo','q1d proof','q2d proof','q3d proof');
grid;
hold off;
subplot(3,1,3);
plot(out.qdd.time,out.qdd.signals.values(:,1));
hold on;
plot(out.qdd.time,out.qdd.signals.values(:,2));
hold on;
plot(out.qdd.time,out.qdd.signals.values(:,3));
hold on;
plot(out.qddp.time,out.qddp.signals.values(:,1));
hold on;
plot(out.qddp.time,out.qddp.signals.values(:,2));
hold on;
plot(out.qddp.time,out.qddp.signals.values(:,3));
title('qdd');
legend('q1dd modelo','q2dd modelo','q3dd modelo','q1dd proof','q2dd proof','q3dd proof');
grid;
hold off;
%----------------------------------------------
figure(2);
set(gcf,'color','w');
sgtitle('Comparación por articulaciones y magnitudes - posición');
subplot(3,1,1);
plot(out.q.time,out.q.signals.values(:,1));
hold on;
plot(out.qp.time,out.qp.signals.values(:,1));
hold off;
legend('q1 modelo','q1 proof');
title('q1');
grid;
subplot(3,1,2);
plot(out.q.time,out.q.signals.values(:,2));
hold on;
plot(out.qp.time,out.qp.signals.values(:,2));
hold off;
legend('q2 modelo','q2 proof');
title('q2');
grid;
subplot(3,1,3);
plot(out.q.time,out.q.signals.values(:,3));
hold on;
plot(out.qp.time,out.qp.signals.values(:,3));
hold off;
legend('q3 modelo','q3 proof');
title('q3');
grid;

figure(3);
set(gcf,'color','w');
sgtitle('Comparación por articulaciones y magnitudes - velocidad');
subplot(3,1,1);
plot(out.qd.time,out.qd.signals.values(:,1));
hold on;
plot(out.qdp.time,out.qdp.signals.values(:,1));
hold off;
legend('q1d modelo','q1d proof');
title('q1d');
grid;
subplot(3,1,2);
plot(out.qd.time,out.qd.signals.values(:,2));
hold on;
plot(out.qdp.time,out.qdp.signals.values(:,2));
hold off;
legend('q2d modelo','q2d proof');
title('q2d');
grid;
subplot(3,1,3);
plot(out.qd.time,out.qd.signals.values(:,3));
hold on;
plot(out.qdp.time,out.qdp.signals.values(:,3));
hold off;
legend('q3d modelo','q3d proof');
title('q3d');
grid;

figure(4);
set(gcf,'color','w');
sgtitle('Comparación por articulaciones y magnitudes - aceleración');
subplot(3,1,1);
plot(out.qdd.time,out.qdd.signals.values(:,1));
hold on;
plot(out.qddp.time,out.qddp.signals.values(:,1));
hold off;
legend('q1dd modelo','q1dd proof');
title('q1dd');
grid;
subplot(3,1,2);
plot(out.qdd.time,out.qdd.signals.values(:,2));
hold on;
plot(out.qddp.time,out.qddp.signals.values(:,2));
hold off;
legend('q2dd modelo','q2dd proof');
title('q2dd');
grid;
subplot(3,1,3);
plot(out.qdd.time,out.qdd.signals.values(:,3));
hold on;
plot(out.qddp.time,out.qddp.signals.values(:,3));
hold off;
legend('q3dd modelo','q3dd proof');
title('q3dd');
grid;